name: Build & Test

on:
  push:
    branches:
      - '*'

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Install Pytest
        run: |
          pip install pytest

      - name: Build Package
        run: |
          python setup.py sdist

      - name: Get Package File Name
        run: |
          $latestFile = Get-ChildItem -Path 'dist\' | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          echo "Latest file: $latestFile"
          echo "PACKAGE_NAME=$latestFile" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Install Package
        run: |
          pip install ${{ env.PACKAGE_NAME }}

      - name: Run Tests
        run: |
          pytest tests -vv -rEPW -o pytest_collection_order=alphabetical --cache-clear --color=yes
